//! Single source of truth for SQL keyword, function, type, and operator constants.
//!
//! Both the syntax highlighter and autocomplete engine import from here
//! instead of maintaining their own duplicate lists.

/// SQL keywords (uppercase for matching; input is uppercased before comparison).
///
/// Union of all keyword lists from the highlighter and autocomplete engine.
/// Sorted alphabetically for maintainability. Does NOT include word operators
/// (AND/OR/NOT) — those are in [`SQL_WORD_OPERATORS`].
///
/// Note: REPLACE appears in both this list and [`SQL_FUNCTIONS`] intentionally.
/// When followed by `(` it is the `REPLACE()` string function; bare `REPLACE`
/// (as in `INSERT OR REPLACE`) is a keyword. Consumers must preserve this
/// precedence logic (check functions before keywords when `(` follows).
pub const SQL_KEYWORDS: &[&str] = &[
    "ABORT",
    "ADD",
    "ALL",
    "ALTER",
    "ANALYZE",
    "ANY",
    "AS",
    "ASC",
    "ATTACH",
    "AUTOINCREMENT",
    "BEGIN",
    "BETWEEN",
    "BY",
    "CASCADE",
    "CASE",
    "CAST",
    "CHECK",
    "COLLATE",
    "COLUMN",
    "COMMIT",
    "CONFLICT",
    "CONSTRAINT",
    "CREATE",
    "CROSS",
    "DEFAULT",
    "DEFERRED",
    "DELETE",
    "DESC",
    "DETACH",
    "DISTINCT",
    "DROP",
    "ELSE",
    "END",
    "ESCAPE",
    "EXCEPT",
    "EXCLUSIVE",
    "EXISTS",
    "EXPLAIN",
    "FAIL",
    "FOREIGN",
    "FROM",
    "GLOB",
    "GROUP",
    "HAVING",
    "IF",
    "IGNORE",
    "IMMEDIATE",
    "IN",
    "INDEX",
    "INNER",
    "INSERT",
    "INTERSECT",
    "INTO",
    "IS",
    "ISNULL",
    "JOIN",
    "KEY",
    "LEFT",
    "LIKE",
    "LIMIT",
    "MATCH",
    "NATURAL",
    "NOCASE",
    "NOTNULL",
    "NULL",
    "OFFSET",
    "ON",
    "ORDER",
    "OUTER",
    "PLAN",
    "PRAGMA",
    "PRIMARY",
    "QUERY",
    "RECURSIVE",
    "REFERENCES",
    "REGEXP",
    "REINDEX",
    "RENAME",
    "REPLACE",
    "RESTRICT",
    "RIGHT",
    "ROLLBACK",
    "ROWID",
    "SELECT",
    "SET",
    "TABLE",
    "TEMP",
    "TEMPORARY",
    "THEN",
    "TRANSACTION",
    "TRIGGER",
    "UNION",
    "UNIQUE",
    "UPDATE",
    "USING",
    "VACUUM",
    "VALUES",
    "VIEW",
    "VIRTUAL",
    "WHEN",
    "WHERE",
    "WITH",
    "WITHOUT",
];

/// Word-form operators — styled differently from keywords in syntax highlighting.
pub const SQL_WORD_OPERATORS: &[&str] = &["AND", "NOT", "OR"];

/// SQL data type names — highlighted distinctly from keywords.
pub const SQL_TYPES: &[&str] = &[
    "BIGINT",
    "BLOB",
    "BOOLEAN",
    "CHAR",
    "DATE",
    "DATETIME",
    "DECIMAL",
    "DOUBLE",
    "FLOAT",
    "INT",
    "INTEGER",
    "NUMERIC",
    "REAL",
    "SMALLINT",
    "TEXT",
    "TIMESTAMP",
    "TINYINT",
    "VARCHAR",
];

/// SQL function names — union of highlighter and autocomplete lists, deduplicated.
///
/// Note: REPLACE appears in both [`SQL_KEYWORDS`] and this list intentionally.
/// When followed by `(` the tokenizer should classify it as a Function.
pub const SQL_FUNCTIONS: &[&str] = &[
    "ABS",
    "AVG",
    "BIN_RECORD_JSON_OBJECT",
    "CAST",
    "CHANGES",
    "COALESCE",
    "COUNT",
    "DATE",
    "DATETIME",
    "FORMAT",
    "FTS_HIGHLIGHT",
    "FTS_MATCH",
    "FTS_SCORE",
    "GENERATE_SERIES",
    "GROUP_CONCAT",
    "HEX",
    "IFNULL",
    "IIF",
    "INSTR",
    "JSON",
    "JSON_ARRAY",
    "JSON_EACH",
    "JSON_EXTRACT",
    "JSON_GROUP_ARRAY",
    "JSON_GROUP_OBJECT",
    "JSON_INSERT",
    "JSON_OBJECT",
    "JSON_PATCH",
    "JSON_REMOVE",
    "JSON_REPLACE",
    "JSON_SET",
    "JSON_TREE",
    "JSON_TYPE",
    "JSON_VALID",
    "JULIANDAY",
    "LAST_INSERT_ROWID",
    "LENGTH",
    "LIBSQL_VECTOR_IDX",
    "LIKELIHOOD",
    "LIKELY",
    "LOWER",
    "LTRIM",
    "MAX",
    "MEDIAN",
    "MIN",
    "NULLIF",
    "PERCENTILE",
    "PERCENTILE_CONT",
    "PERCENTILE_DISC",
    "PRINTF",
    "QUOTE",
    "RANDOM",
    "RANDOMBLOB",
    "REGEXP_CAPTURE",
    "REGEXP_REPLACE",
    "REGEXP_SUBSTR",
    "REPLACE",
    "ROUND",
    "RTRIM",
    "STDDEV",
    "STRFTIME",
    "SUBSTR",
    "SUBSTRING",
    "SUM",
    "TABLE_COLUMNS_JSON_ARRAY",
    "TIME",
    "TIMEDIFF",
    "TIME_ADD",
    "TIME_DATE",
    "TIME_FMT_DATETIME",
    "TIME_FMT_ISO",
    "TIME_FMT_UNIXEPOCH",
    "TIME_NOW",
    "TIME_SUB",
    "TIME_UNIX",
    "TOTAL",
    "TOTAL_CHANGES",
    "TRIM",
    "TYPEOF",
    "UNICODE",
    "UNIXEPOCH",
    "UNLIKELY",
    "UPPER",
    "UUID4",
    "UUID7",
    "UUID7_TIMESTAMP_MS",
    "UUID_BLOB",
    "UUID_STR",
    "VECTOR32",
    "VECTOR64",
    "VECTOR_CONCAT",
    "VECTOR_DIMENSION",
    "VECTOR_DISTANCE_COS",
    "VECTOR_DISTANCE_L2",
    "VECTOR_EXTRACT",
    "VECTOR_SLICE",
    "VECTOR_TOP_K",
    "ZEROBLOB",
];

/// `SQLite` base types (affinity types). Pure SQL knowledge.
pub const BASE_TYPES: &[&str] = &["ANY", "BLOB", "INTEGER", "REAL", "TEXT"];

// ─── Autocomplete-specific keyword subsets ───────────────────────────────────

/// Keywords that directly introduce a table name (the next token is a table).
pub const TABLE_CONTEXT_KEYWORDS: &[&str] = &["FROM", "INTO", "JOIN", "TABLE", "UPDATE"];

/// JOIN qualifier keywords — after these the next expected token is `JOIN`.
pub const JOIN_QUALIFIER_KEYWORDS: &[&str] =
    &["CROSS", "INNER", "LEFT", "NATURAL", "OUTER", "RIGHT"];

/// Keywords that introduce a column/expression context.
pub const COLUMN_CONTEXT_KEYWORDS: &[&str] = &[
    "AND", "BY", "GROUP", "HAVING", "ON", "OR", "ORDER", "SELECT", "SET", "WHERE",
];

/// Statement-starting keywords (for autocomplete top-level suggestions).
pub const STATEMENT_KEYWORDS: &[&str] = &[
    "ALTER", "ANALYZE", "ATTACH", "BEGIN", "COMMIT", "CREATE", "DELETE", "DETACH", "DROP",
    "EXPLAIN", "INSERT", "PRAGMA", "REINDEX", "ROLLBACK", "SELECT", "UPDATE", "VACUUM", "WITH",
];

/// Combined clause-level keywords offered in expression context.
pub const CLAUSE_KEYWORDS: &[&str] = &[
    "ALL",
    "AND",
    "AS",
    "ASC",
    "BETWEEN",
    "BY",
    "CASE",
    "CROSS",
    "DEFAULT",
    "DESC",
    "DISTINCT",
    "ELSE",
    "END",
    "EXCEPT",
    "EXISTS",
    "FROM",
    "GROUP",
    "HAVING",
    "IN",
    "INNER",
    "INTERSECT",
    "INTO",
    "IS",
    "JOIN",
    "LEFT",
    "LIKE",
    "LIMIT",
    "NOT",
    "NULL",
    "OFFSET",
    "ON",
    "OR",
    "ORDER",
    "OUTER",
    "RIGHT",
    "SELECT",
    "SET",
    "THEN",
    "UNION",
    "VALUES",
    "WHEN",
    "WHERE",
];

/// Filter/expression keywords used by the autocomplete `is_sql_keyword()` check.
///
/// These were previously hardcoded in a `matches!()` block. Now a proper constant
/// so that all keyword knowledge lives in one place.
pub const FILTER_KEYWORDS: &[&str] = &[
    "AND",
    "AS",
    "BETWEEN",
    "CASE",
    "DEFAULT",
    "ELSE",
    "END",
    "EXCEPT",
    "EXISTS",
    "GROUP",
    "HAVING",
    "IN",
    "INTERSECT",
    "IS",
    "LIKE",
    "LIMIT",
    "NOT",
    "NULL",
    "OFFSET",
    "ON",
    "OR",
    "ORDER",
    "SET",
    "THEN",
    "UNION",
    "VALUES",
    "WHEN",
    "WHERE",
];
